### ISSUE TITLE
routing is not a constructor?

### ISSUE THREAD

**Issue by johnshumon** [gimox/json-routing#5]
Taken example from your repository. Here is my code:
```
const
    express = require('express'),
    morgan = require('morgan'),
    routing = require('json-routing'),
    appRootDir = require('app-root-dir').get(),
    port = process.env.PORT || 8096
    ;

let routeOptions = {
    routesPath      : appRootDir + "/api/routes",
    controllerPath  : appRootDir + "/api/controllers",
    cors            : true,
    displayRoute    : true,
    defaultAction   : "index",
    processDir		: process.cwd()
};

let app = express();
app.set(morgan('combined'));
new routing(app, routeOptions);
app.listen(port, function () {
    console.log(`Server running on http://127.0.0.1:${port})`)
});
```

gives following error! 
```
new routing(app, routeOptions);
^
TypeError: routing is not a constructor
    at Object.<anonymous> (/home/shumon/workspace/api-gw/mock-server/app.js:24:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by gimox** [comment]
are you using version >= 2.x?

**Comment by gimox** [comment]
There is a type in doc!!!!

try this: 


```js
const express = require('express');
const app = express();
const Routing = require("json-routing");

// so make attention on new Routing.JsonRoute

let routeInfo = new Routing.JsonRoute(app, {
    "routesPath": "./api/routes",
    "processdir": __dirname
}).start();

const server = app.listen(3000, () => {
    console.log("Listening on port %d", server.address().port);
})
```

doc fix is on the fly!

**Comment by johnshumon** [comment]
yeah i'm using version `>=2.x`  and also my bad i didn't check in details. thanks for the quick fix. it's working now.

**Comment by gimox** [comment]
Good!!
